name: app2
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  http: ^1.6.0
  # path: ^1.8.0

http: ^1.6.0